title: Sivuyiso Mvani
logo: assets/Sivuyiso (2).JPG
description: Final year BSc Applied Statistics student at the University of Cape Town (UCT) with a passion for using data to drive informed decision-making and solve real-world challenges.
show_downloads: False
theme: jekyll-theme-minimal
