title: Sivuyiso Mvani
logo: assets/Sivuyiso (2).JPG
description: Final year BSc Applied Statistics student at the University of Cape Town (UCT) with a passion for using data to drive informed decision-making and solve real-world challenges. Throughout my academic journey, I’ve honed my skills in data analysis, statistical modelling, and computational programming in languages like Python, R, and MATLAB. I am currently seeking internship opportunities in the field of data analytics & data science.
show_downloads: False
theme: jekyll-theme-minimal
